"""user tokens

Revision ID: 930bdac27537
Revises: c2b4c10bb640
Create Date: 2021-09-21 16:15:29.632407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '930bdac27537'
down_revision = 'c2b4c10bb640'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('token_expiration', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_token'), 'user', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_token'), table_name='user')
    op.drop_column('user', 'token_expiration')
    op.drop_column('user', 'token')
    # ### end Alembic commands ###
